import {StyleSheet, Dimensions} from 'react-native';
const {width, height} = Dimensions.get('window');
const Styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: '#fff',
  },
  mainBody: {
    height: 300,
    backgroundColor: '#0c7ec4',
    borderBottomStartRadius: 50,
    borderBottomEndRadius: 50,
  },
  txtContainer: {
    color: '#000',
  },
  headerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 10,
    margin: 10,
  },
  imgConatainer: {
    paddingRight: 10,
  },

  imgStyles: {
    height: 80,
    width: 80,
    borderRadius: 17,
  },
  monthContainer: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    padding: 10,
  },
  topupTxt: {
    color: '#EE811F',
    fontSize: 16,
  },
  cardTxt: {
    color: '#fff',
    fontSize: 20,
  },
  balanceTxt: {
    color: '#000',
    fontSize: 20,
  },
  inrTxt: {
    color: '#3a3185',
    fontSize: 14,
  },
  inrTxt2: {
    // color: '#EE811F',
    color: '#3a3185',
    fontSize: 14,
  },
  hdTxt: {
    color: '#EE811F',
    fontSize: 18,
    fontWeight: 'bold',
  },
  rtTxt: {
    color: '#45A581',
    fontSize: 16,
  },
  priceTxt: {
    color: '#fff',
    fontSize: 24,
    paddingLeft: 10,
    fontWeight: 'bold',
  },
  priceTxt2: {
    color: '#fff',
    fontSize: 20,
    paddingLeft: 20,
  },
  topupBody: {
    backgroundColor: '#fff',
    borderRadius: 11,
    height: 50,
    width: 100,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    marginTop: 10,
  },

  cardBody: {
    backgroundColor: '#fff',
    borderRadius: 9,
    height: 25,
    width: 35,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  cardContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignSelf: 'center',
    padding: 20,
    zIndex: 3,
    width: width - 20,
    height: 550,
    bottom: 200,
    borderWidth: 1,
    backgroundColor: '#A3C1F5',
    borderColor: 'gray',
    borderRadius: 7,
  },
  RequestBtn: {
    padding: 20,
    width: width - 20,
    height: 50,
    backgroundColor: '#A3C1F5',
    borderRadius: 7,
  },
  priceConatiner: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  TransBody: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    padding: 10,
  },
  allBody: {
    backgroundColor: '#fff',
    borderRadius: 11,
    height: 60,
    width: 150,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mouseIconStyle: {
    height: 50,
    width: 50,
    borderRadius: 50,
    marginHorizontal: 10,
  },
  flatContainer: {
    backgroundColor: '#f5f2f2',
    flexDirection: 'row',
    width: '90%',
    height: 70,
    margin: 1,
    alignSelf: 'center',
    alignItems: 'center',
    borderColor: 'grey',
    borderRadius: 11,
  },
  flatText: {
    color: '#EE811F',
    fontSize: 16,
    fontWeight: 'bold',
  },
  flatText2: {
    color: 'gray',
    fontSize: 14,
    bottom: 30,
  },
  ParentContainer: {
    flex: 1,
    padding: 10,
    backgroundColor: '#777777',
  },
  menuStyle: {
    color: 'white',
    fontSize: 20,
    paddingRight: 70,
  },
  ftTxt: {
    color: '#fff',
    fontSize: 18,
    textAlign: 'center',
    bottom: 10,
  },
  Usertxt: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 22,
  },
  EditText: {
    color: '#000',
    // fontWeight: 'bold',
    fontSize: 18,
    paddingRight: 90,
  },
  saveText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 20,
    textAlign: 'center',
  },
  EditContainer: {
    backgroundColor: '#fff',
    height: 30,
    width: 30,
    borderRadius: 50,
    zIndex: 2,
    alignSelf: 'center',
    bottom: 30,
    left: 45,
    alignItems: 'center',
    justifyContent: 'center',
  },
  Useridenty: {
    color: '#ddd',
    fontSize: 14,
    paddingLeft: 5,
    paddingVertical: 3,
  },
  imglogoContainer: {
    alignSelf: 'center',
    borderRadius: 50,
  },
  userlogoStyle: {
    height: 150,
    width: 150,
    alignItems: 'center',
    borderRadius: 50,
  },
  profileContainer: {
    backgroundColor: '#0c7ec4',
    height: height - 500,
    padding: 10,
    paddingTop: 20,
    zIndex: 1,
  },
  CameraStyle: {},

  rdxContainer: {
    // flexDirection: 'row',
    // justifyContent: 'space-evenly',
  },
  InputContainer: {
    height: 45,
    borderColor: 'gray',
    borderWidth: 0.2,
    padding: 10,
    margin: 20,
    borderRadius: 5,
    color: 'black',
  },
  mainInputContainer: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: '#E3E4EE',
    zIndex: 1,
  },
  boxContainer: {
    top: 100,
    borderRadius: 5,
    backgroundColor: '#fff',
    borderColor: 'gray',
    width: width - 20,
    height: 600,
    alignSelf: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.5,
    shadowRadius: 3,
    shadowOffset: {
      height: 0.5,
      width: 1,
    },
  },
  SaveContainer: {
    backgroundColor: '#0c7ec4',
    padding: 10,
    margin: 15,
    borderRadius: 10,
    marginTop: 80,
  },
  lableOne: {
    color: '#000',
    fontSize: 16,
    padding: 10,
    margin: 10,
  },
  lable: {
    textAlign: 'center',
    color: '#000',
    fontSize: 20,
    padding: 10,
    fontWeight: 'bold',
  },
  iconCalender: {
    position: 'absolute',
    alignSelf: 'flex-end',
    margin: 10,
    padding: 20,
    right: 5,
  },
  icon: {
    position: 'absolute',
    alignSelf: 'flex-end',
    margin: 10,
    padding: 20,
    right: 5,
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalView: {
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 40,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  button: {
    borderRadius: 20,
    padding: 10,
    elevation: 2,
  },
  buttonOpen: {
    backgroundColor: '#F194FF',
  },
  buttonClose: {
    backgroundColor: '#2196F3',
  },
  textStyle: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  modalText: {
    marginBottom: 15,
    textAlign: 'center',
  },
  c1: {
    borderWidth: 1,
    borderColor: 'gray',
    height: 400,
  },
  c2: {
    margin: 5,
    right: 10,
  },
  c3: {
    color: 'black',
    paddingLeft: 5,
  },
  c10: {
    padding: 10,
    bottom: 15,
    width: width - 80,
    alignSelf: 'center',
    borderWidth: 0.3,
    borderColor: 'gray',
    borderRadius: 5,
  },
});

export default Styles;
