import {StyleSheet, Dimensions} from 'react-native';
const {width, height} = Dimensions.get('window');
const Styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: '#fff',
  },
  ListContainer: {
    flex: 1,
  },
  rowContainer: {
    padding: 10,
    margin: 10,
    width: '95%',
    height: 200,
    backgroundColor: '#f7f7f7',
    // backgroundColor: '#0c7ec4',
    // backgroundColor: '#0c7ec4',
    borderRadius: 11,
    justifyContent: 'center',
  },
  btnContainer: {
    alignItems: 'center',
  },
  logoview: {
    alignItems: 'center',
  },
  logoStyle: {
    borderRadius: 9,
  },
  txtContainer: {
    color: 'gray',
    fontSize: 14,
    fontFamily: 'Roboto',
  },
  headerView: {
    flexDirection: 'row',
    borderBottomWidth: 0.4,
    justifyContent: 'space-between',
    borderColor: 'gray',
    padding: 10,
    backgroundColor: '#0c7ec4',
  },
  txtWelcome: {
    color: '#000',
    // color: '#fff',
    // fontWeight: 'bold',
    fontSize: 20,
  },
  ftTxt: {
    color: '#fff',
    fontSize: 22,
  },
  imgContainer: {
    height: 300,
    width: 300,
  },
  imgViewContainer: {
    padding: 10,
    paddingTop: 50,
    alignItems: 'center',
  },
  flatimg: {
    width: 300,
    height: 300,
    right: '1%',
    alignSelf: 'center',
    borderColor: 'rgba(0, 0, 0, 0.18)',
  },
  modalContainer: {
    height: '50%',
    width: width - 1,
    margin: 0.5,
    padding: 10,
    backgroundColor: '#3a3185',
    borderTopLeftRadius: 17,
    borderTopRightRadius: 17,
    alignSelf: 'center',
  },
  Usertxt: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 24,
    textAlign: 'center',
    paddingTop: 10,
  },
  EditText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 20,
    textAlign: 'center',
    paddingRight: 60,
  },
  Useridenty: {
    color: '#5C6468',
    fontSize: 16,
    textAlign: 'center',
  },
  Gettxt: {
    color: '#3a3185',
    fontSize: 20,
    textAlign: 'center',
    fontFamily: 'sans-serif',
  },
  mainBody: {
    padding: 10,
  },
  SectionStyle: {
    flexDirection: 'row',
    height: 50,
    marginTop: 20,
    marginLeft: 35,
    marginRight: 35,
    margin: 10,
  },
  buttonStyle: {
    backgroundColor: '#rgb(238,129,31)',
    borderWidth: 0,
    color: '#FFFFFF',
    borderColor: '#7DE24E',
    height: 40,
    alignItems: 'center',
    borderRadius: 30,
    marginLeft: 35,
    marginRight: 35,
    marginTop: 20,
    marginBottom: 25,
  },
  buttonTextStyle: {
    color: '#FFFFFF',
    paddingVertical: 10,
    fontSize: 16,
  },

  inputStyle: {
    flex: 1,
    color: 'white',
    paddingLeft: 15,
    paddingRight: 15,
    borderWidth: 1,
    borderRadius: 30,
    borderColor: '#dadae8',
  },
  registerTextStyle: {
    color: '#3a3185',
    textAlign: 'center',
    fontWeight: 'bold',
    fontSize: 14,
    alignSelf: 'center',
    padding: 10,
  },
  errorTextStyle: {
    color: 'red',
    textAlign: 'center',
    fontSize: 14,
  },
  imglogoContainer: {
    alignItems: 'center',
    paddingTop: 50,
    borderRadius: 90,
  },
  userlogoStyle: {
    height: 150,
    width: 150,
    borderRadius: 50,
  },
  profileContainer: {
    // backgroundColor: '#3a3185',
    backgroundColor: '#0c7ec4',
    height: height - 500,
  },
  DataContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 10,
  },
  BoxContainer2: {
    backgroundColor: '#D6D8F5',
    height: 40,
    width: 40,
    borderRadius: 12,
    justifyContent: 'center',
    alignSelf: 'center',
  },
  BoxContainer3: {
    backgroundColor: '#F1DBBD',
    height: 40,
    width: 40,
    borderRadius: 12,
    justifyContent: 'center',
    alignSelf: 'center',
  },
  BoxContainer4: {
    backgroundColor: '#99E987',
    height: 40,
    width: 40,
    borderRadius: 12,
    justifyContent: 'center',
    alignSelf: 'center',
  },
  BoxContainer5: {
    backgroundColor: '#D6D8F5',
    height: 40,
    width: 40,
    borderRadius: 12,
    justifyContent: 'center',
    alignSelf: 'center',
  },
  EmployeeContainer: {
    paddingRight: 10,
  },
  txttContainer: {},

  mainBody2: {
    height: 400,
    // backgroundColor: '#2D9AF5',
    backgroundColor: '#0c7ec4',
    borderBottomStartRadius: 50,
    borderBottomEndRadius: 50,
  },
  imgStyles: {
    height: 80,
    width: 80,
    borderRadius: 17,
  },

  flatContainer: {
    backgroundColor: '#f5f2f2',
    flexDirection: 'row',
    width: '95%',
    height: 70,
    alignSelf: 'center',
    alignItems: 'center',
    borderColor: 'grey',
    borderRadius: 11,
    padding: 10,
  },
  flatText: {
    color: '#000',
    fontSize: 14,
  },
  flatText2: {
    color: '#918c87',
    fontSize: 15,
    // fontWeight: 'bold',
  },
  c7: {
    flex: 1,
    justifyContent: 'center',
    paddingTop: 20,
  },
  c8: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  c9: {
    padding: 10,
    margin: 1,
    paddingTop: 10,
  },
  c10: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
});

export default Styles;
